const productsData = [
    // --- Original 6 Products (001 to 006) ---
    {
        sku: "GPN–001",
        name: "Gold Plated Temple Necklace Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,999",
        mrp: "₹2,999",
        stock: 45,
        category: "Necklaces",
        rating: 4.8,
    },
    {
        sku: "ALH–002",
        name: "Antique Finish Long Haar with Jhumkas",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹2,499",
        mrp: "₹3,999",
        stock: 28,
        category: "Necklaces",
        rating: 4.7,
    },
    {
        sku: "TJE–003",
        name: "Traditional Jhumka Earrings",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹799",
        mrp: "₹1,299",
        stock: 82,
        category: "Earrings",
        rating: 4.9,
    },
    {
        sku: "DBS–004",
        name: "Designer Bangles Set (6 Pieces)",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,899",
        mrp: "₹2,899",
        stock: 15,
        category: "Bangles",
        rating: 4.6,
    },
    {
        sku: "PDC–005",
        name: "Peacock Design Choker Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,799",
        mrp: "₹2,799",
        stock: 5,
        category: "Necklaces",
        rating: 4.8,
    },
    {
        sku: "KME–006",
        name: "Kundan Meenakari Earrings",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Draft",
        price: "₹1,299",
        mrp: "₹1,999",
        stock: 0,
        category: "Earrings",
        rating: null,
    },

    // --- Products 007 to 031 (Previously Generated 25) ---
    {
        sku: "RST–007",
        name: "Ruby Stone Studded Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹899",
        mrp: "₹1,499",
        stock: 95,
        category: "Rings",
        rating: 4.7,
    },
    {
        sku: "JHS–008",
        name: "Heavy Bridal Jhumka Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹2,999",
        mrp: "₹4,500",
        stock: 12,
        category: "Earrings",
        rating: 4.9,
    },
    {
        sku: "ADR–009",
        name: "American Diamond Kada Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Draft",
        price: "₹1,199",
        mrp: "₹1,899",
        stock: 0,
        category: "Rings",
        rating: null,
    },
    {
        sku: "GCT–010",
        name: "German Silver Coin Necklace",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,650",
        mrp: "₹2,500",
        stock: 33,
        category: "Necklaces",
        rating: 4.6,
    },
    {
        sku: "MBS–011",
        name: "Matte Finish Bangles (Set of 4)",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹750",
        mrp: "₹1,100",
        stock: 77,
        category: "Bangles",
        rating: 4.5,
    },
    {
        sku: "PNR–012",
        name: "Pearl Nagas Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹950",
        mrp: "₹1,599",
        stock: 22,
        category: "Rings",
        rating: 4.8,
    },
    {
        sku: "EFS–013",
        name: "Emerald Fashion Studs",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Archived",
        price: "₹499",
        mrp: "₹799",
        stock: 1,
        category: "Earrings",
        rating: 4.2,
    },
    {
        sku: "TCH–014",
        name: "Thin Crystal Choker",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,200",
        mrp: "₹1,800",
        stock: 40,
        category: "Necklaces",
        rating: 4.7,
    },
    {
        sku: "SBS–015",
        name: "Silver Plated Solid Bangles",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,050",
        mrp: "₹1,600",
        stock: 18,
        category: "Bangles",
        rating: 4.6,
    },
    {
        sku: "PLJ–016",
        name: "Polki Layered Jhumkas",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,450",
        mrp: "₹2,200",
        stock: 30,
        category: "Earrings",
        rating: 4.8,
    },
    {
        sku: "HCS–017",
        name: "Handcrafted Temple Chain Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹3,500",
        mrp: "₹5,200",
        stock: 8,
        category: "Necklaces",
        rating: 4.9,
    },
    {
        sku: "ZIR–018",
        name: "Zircon Solitaire Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹699",
        mrp: "₹1,099",
        stock: 55,
        category: "Rings",
        rating: 4.5,
    },
    {
        sku: "GRS–019",
        name: "Ganesha Relief Studs",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Draft",
        price: "₹550",
        mrp: "₹950",
        stock: 0,
        category: "Earrings",
        rating: null,
    },
    {
        sku: "ABS–020",
        name: "Antique Bridal Bangles Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹2,100",
        mrp: "₹3,300",
        stock: 10,
        category: "Bangles",
        rating: 4.7,
    },
    {
        sku: "TGR–021",
        name: "Traditional Gold Tone Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹450",
        mrp: "₹650",
        stock: 110,
        category: "Rings",
        rating: 4.4,
    },
    {
        sku: "RTS–022",
        name: "Rose Gold Tone Necklace Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,599",
        mrp: "₹2,499",
        stock: 25,
        category: "Necklaces",
        rating: 4.7,
    },
    {
        sku: "DJS–023",
        name: "Delicate Jali Work Studs",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹850",
        mrp: "₹1,300",
        stock: 70,
        category: "Earrings",
        rating: 4.6,
    },
    {
        sku: "LGS–024",
        name: "Lakshmi Goddess Necklace",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Archived",
        price: "₹2,700",
        mrp: "₹4,100",
        stock: 3,
        category: "Necklaces",
        rating: 4.8,
    },
    {
        sku: "ADJ–025",
        name: "AD Hoop Earrings",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,150",
        mrp: "₹1,850",
        stock: 38,
        category: "Earrings",
        rating: 4.5,
    },
    {
        sku: "FLB–026",
        name: "Floral Enamel Bangles",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,400",
        mrp: "₹2,100",
        stock: 11,
        category: "Bangles",
        rating: 4.6,
    },
    {
        sku: "MTS–027",
        name: "Multi-Tiered Statement Necklace",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,999",
        mrp: "₹3,199",
        stock: 19,
        category: "Necklaces",
        rating: 4.7,
    },
    {
        sku: "TRD–028",
        name: "Triple Layered Droplet Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Draft",
        price: "₹799",
        mrp: "₹1,299",
        stock: 0,
        category: "Rings",
        rating: null,
    },
    {
        sku: "PKJ–029",
        name: "Polki Kundan Jhumkas",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,699",
        mrp: "₹2,699",
        stock: 27,
        category: "Earrings",
        rating: 4.8,
    },
    {
        sku: "SBB–030",
        name: "Stackable Beaded Bracelets",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹350",
        mrp: "₹550",
        stock: 150,
        category: "Bangles",
        rating: 4.3,
    },
    {
        sku: "GCT–031",
        name: "Geometric Cutout Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹950",
        mrp: "₹1,450",
        stock: 42,
        category: "Rings",
        rating: 4.6,
    },

    // --- 20 Newly Generated Products (032 to 051) ---
    {
        sku: "VCS–032",
        name: "Victorian Chain Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹3,100",
        mrp: "₹4,800",
        stock: 14,
        category: "Necklaces",
        rating: 4.8,
    },
    {
        sku: "MDS–033",
        name: "Minimalist Drop Studs",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹599",
        mrp: "₹899",
        stock: 65,
        category: "Earrings",
        rating: 4.5,
    },
    {
        sku: "TBR–034",
        name: "Textured Brass Kada Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Archived",
        price: "₹850",
        mrp: "₹1,250",
        stock: 2,
        category: "Rings",
        rating: 4.1,
    },
    {
        sku: "BWR–035",
        name: "Braided Wire Bangles (Set of 2)",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹699",
        mrp: "₹1,050",
        stock: 50,
        category: "Bangles",
        rating: 4.4,
    },
    {
        sku: "HNS–036",
        name: "Heavy Stone Halter Necklace",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹4,200",
        mrp: "₹6,500",
        stock: 5,
        category: "Necklaces",
        rating: 4.9,
    },
    {
        sku: "KPR–037",
        name: "Kundan Petal Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,099",
        mrp: "₹1,799",
        stock: 31,
        category: "Rings",
        rating: 4.7,
    },
    {
        sku: "AES–038",
        name: "Antique Elephant Studs",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹950",
        mrp: "₹1,400",
        stock: 20,
        category: "Earrings",
        rating: 4.6,
    },
    {
        sku: "DBT–039",
        name: "Delicate Beaded Tassels Choker",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,450",
        mrp: "₹2,150",
        stock: 29,
        category: "Necklaces",
        rating: 4.5,
    },
    {
        sku: "PCS–040",
        name: "Plain Copper Cuff Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Draft",
        price: "₹500",
        mrp: "₹750",
        stock: 0,
        category: "Bangles",
        rating: null,
    },
    {
        sku: "FDR–041",
        name: "Filigree Design Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹750",
        mrp: "₹1,199",
        stock: 75,
        category: "Rings",
        rating: 4.3,
    },
    {
        sku: "RTS–042",
        name: "Rajputana Tassel Earrings",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,800",
        mrp: "₹2,900",
        stock: 17,
        category: "Earrings",
        rating: 4.8,
    },
    {
        sku: "JNL–043",
        name: "Jali Work Nagas Long Necklace",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹3,999",
        mrp: "₹6,000",
        stock: 9,
        category: "Necklaces",
        rating: 4.9,
    },
    {
        sku: "EAB–044",
        name: "Enamel Art Bangles (Pair)",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,550",
        mrp: "₹2,300",
        stock: 23,
        category: "Bangles",
        rating: 4.7,
    },
    {
        sku: "GDR–045",
        name: "Gemstone Dome Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,350",
        mrp: "₹2,100",
        stock: 13,
        category: "Rings",
        rating: 4.6,
    },
    {
        sku: "BMS–046",
        name: "Bohemian Mirror Earrings",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹650",
        mrp: "₹999",
        stock: 88,
        category: "Earrings",
        rating: 4.4,
    },
    {
        sku: "CRS–047",
        name: "Circular Ruby Stone Necklace",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹2,200",
        mrp: "₹3,300",
        stock: 16,
        category: "Necklaces",
        rating: 4.7,
    },
    {
        sku: "DCS–048",
        name: "Diamond-Cut Bangles (4pc)",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,750",
        mrp: "₹2,700",
        stock: 7,
        category: "Bangles",
        rating: 4.8,
    },
    {
        sku: "TJR–049",
        name: "Traditional Temple Jewelry Ring",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Draft",
        price: "₹999",
        mrp: "₹1,599",
        stock: 0,
        category: "Rings",
        rating: null,
    },
    {
        sku: "PND–050",
        name: "Pearl Nagas Drop Earrings",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,399",
        mrp: "₹2,100",
        stock: 24,
        category: "Earrings",
        rating: 4.6,
    },
    {
        sku: "WBS–051",
        name: "Wide Engraved Bangle Set",
        seller: "Rajasekhar",
        img: "https://via.placeholder.com/45",
        status: "Active",
        price: "₹1,950",
        mrp: "₹3,000",
        stock: 6,
        category: "Bangles",
        rating: 4.7,
    },
];

export default productsData;
